import type { Icon } from "@tabler/icons-react";
import {
  IconFile,
  IconBrandNodejs,
  IconBrandTypescript,
  IconBrandDocker,
  IconBrandGit,
  IconBrandRust,
  IconTerminal,
  IconLock,
  IconBrandTailwind,
  IconBrandSass,
  IconBrandPython,
  IconBrandGolang,
  IconBrandSvelte,
  IconFileTypeTs,
  IconFileTypeTsx,
  IconFileTypeJs,
  IconFileTypeJsx,
  IconFileTypeHtml,
  IconFileTypeCss,
  IconFileTypeRs,
  IconFileTypeSql,
  IconFileTypeSvg,
  IconFileTypeXml,
  IconFileTypeZip,
  IconFileTypePdf,
  IconFileTypeCsv,
  IconFileTypeTxt,
  IconFileTypePhp,
  IconFileTypeVue,
  IconJson,
  IconMarkdown,
  IconPhoto,
  IconMusic,
  IconVideo,
  IconCode,
} from "@tabler/icons-react";

const SPECIAL_FILENAMES: Record<string, Icon> = {
  "package.json": IconBrandNodejs,
  "package-lock.json": IconBrandNodejs,
  "yarn.lock": IconBrandNodejs,
  "pnpm-lock.yaml": IconBrandNodejs,
  "tsconfig.json": IconBrandTypescript,
  "jsconfig.json": IconBrandTypescript,
  dockerfile: IconBrandDocker,
  "docker-compose.yml": IconBrandDocker,
  "docker-compose.yaml": IconBrandDocker,
  ".dockerignore": IconBrandDocker,
  ".gitignore": IconBrandGit,
  ".gitattributes": IconBrandGit,
  ".gitmodules": IconBrandGit,
  "cargo.toml": IconBrandRust,
  "cargo.lock": IconBrandRust,
  makefile: IconTerminal,
  gnumakefile: IconTerminal,
  license: IconLock,
  "license.md": IconLock,
  "license.txt": IconLock,
  ".edity": IconJson,
};

const EXTENSION_MAP: Record<string, Icon> = {
  ts: IconFileTypeTs,
  tsx: IconFileTypeTsx,
  js: IconFileTypeJs,
  mjs: IconFileTypeJs,
  cjs: IconFileTypeJs,
  jsx: IconFileTypeJsx,
  json: IconJson,
  html: IconFileTypeHtml,
  htm: IconFileTypeHtml,
  css: IconFileTypeCss,
  scss: IconBrandSass,
  sass: IconBrandSass,
  less: IconFileTypeCss,
  md: IconMarkdown,
  mdx: IconMarkdown,
  py: IconBrandPython,
  rs: IconFileTypeRs,
  go: IconBrandGolang,
  vue: IconFileTypeVue,
  svelte: IconBrandSvelte,
  sql: IconFileTypeSql,
  svg: IconFileTypeSvg,
  xml: IconFileTypeXml,
  php: IconFileTypePhp,
  csv: IconFileTypeCsv,
  txt: IconFileTypeTxt,
  pdf: IconFileTypePdf,
  zip: IconFileTypeZip,
  tar: IconFileTypeZip,
  gz: IconFileTypeZip,
  rar: IconFileTypeZip,
  "7z": IconFileTypeZip,
  png: IconPhoto,
  jpg: IconPhoto,
  jpeg: IconPhoto,
  gif: IconPhoto,
  bmp: IconPhoto,
  webp: IconPhoto,
  ico: IconPhoto,
  mp3: IconMusic,
  wav: IconMusic,
  ogg: IconMusic,
  flac: IconMusic,
  mp4: IconVideo,
  mov: IconVideo,
  avi: IconVideo,
  webm: IconVideo,
  sh: IconTerminal,
  bash: IconTerminal,
  zsh: IconTerminal,
  fish: IconTerminal,
  yml: IconCode,
  yaml: IconCode,
  toml: IconCode,
  ini: IconCode,
  cfg: IconCode,
  conf: IconCode,
  c: IconCode,
  cpp: IconCode,
  h: IconCode,
  hpp: IconCode,
  java: IconCode,
  kt: IconCode,
  swift: IconCode,
  cs: IconCode,
  rb: IconCode,
  r: IconCode,
  dart: IconCode,
  lua: IconCode,
  graphql: IconCode,
  gql: IconCode,
};

const PREFIX_PATTERNS: Array<[string, Icon]> = [
  [".env", IconLock],
  ["tailwind.config", IconBrandTailwind],
  ["vite.config", IconCode],
  ["webpack.config", IconCode],
  ["eslint", IconCode],
  ["prettier", IconCode],
];

export function getFileIcon(filename: string): Icon {
  const lower = filename.toLowerCase();

  const special = SPECIAL_FILENAMES[lower];
  if (special) return special;

  for (const [prefix, icon] of PREFIX_PATTERNS) {
    if (lower.startsWith(prefix)) return icon;
  }

  const ext = lower.split(".").pop() ?? "";
  return EXTENSION_MAP[ext] ?? IconFile;
}
